### ISSUE TITLE
Unable to sync with CPP Boost Named Semaphores

### ISSUE THREAD

**Issue by Berttwm** [ralexander-phi/semaphore_win_ctypes#14]
* Windows Semaphore ctypes version:
* Python version: 3.7 (tried on 3.9 as well)
* Operating System: Windows 10

### Description

I am unable to `open()` the instantiated semaphore. This is my python code. As you can see, I have commented out everything but the `.open()` code. 
```
if __name__ == '__main__':
        cpp_semaphore = "CPPSem" # Pre-determined by CPP program
	# Initialize shared memory region
	semaphore = Semaphore(cpp_semaphore)
	try:
		semaphore.open()
		# semaphore.acquire(timeout_ms=0)
		# # Perform work here
		# semaphore.release()
	finally:
		semaphore.close()
```
I have a separate CPP routine running which has created the named semaphore using boost libraries and the CPP routine has not closed the semaphore yet. I am using the named semaphore simply as a means to synchronize access to shared memory between my python routine and this CPP routine.

![image](https://user-images.githubusercontent.com/44689249/158987152-d211173b-4604-45bb-be07-9c0e4202bb61.png)
CPP Code for reference. 
### What I Did

I have run the CPP code until line 39 where I am waiting to `post()` the semaphore. I am constantly faced with this error on the python code and python seems to be unable to find the named semaphore to open? (I am not sure if this is truly the case)
Below is the log from running the python routine. 
```
Traceback (most recent call last):
  File "PyReader.py", line 52, in <module>
    semaphore.open()
  File "C:\Users\User\anaconda3\envs\msgrpc\lib\site-packages\semaphore_win_ctypes\__init__.py", line 162, in open
    raise WinError()
FileNotFoundError: [WinError 2] The system cannot find the file specified.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PyReader.py", line 57, in <module>
    semaphore.close()
  File "C:\Users\User\anaconda3\envs\msgrpc\lib\site-packages\semaphore_win_ctypes\__init__.py", line 226, in close
    raise WinError()
OSError: [WinError 6] The handle is invalid.
```

I am able to use this to successfully `.create()` and use the created semaphores within python but it does not seem to synchronize with CPP boost created named semaphores. 

If this is not yet supported, how do you synchronize CPP and python semaphores in your tests?

**Comment by ralexander-phi** [comment]
Hi Bertrand,

The C++ code for the tests is [over here](https://github.com/ralexander-phi/windows-semaphore-helper/blob/main/SemaphoreHelper/SemaphoreHelper.cpp). The test uses the Windows API directly, so I don't have a boost example.

Looking at the boost source code, it looks like [`named_semaphore`](https://github.com/boostorg/interprocess/blob/0fcdbc4083aac62e5e2f801a64e00afd5ee6e681/include/boost/interprocess/sync/named_semaphore.hpp) uses [windows/named_semaphore](https://github.com/boostorg/interprocess/blob/0fcdbc4083aac62e5e2f801a64e00afd5ee6e681/include/boost/interprocess/sync/windows/named_semaphore.hpp) on Windows. That ends up calling [`CreateSemaphoreA()`](https://github.com/boostorg/interprocess/blob/a3c27fff1fcab9b662f2cd3aa3f5029018973ec4/include/boost/interprocess/detail/win32_api.hpp#L765) and similar functions, so I believe boost and this project are compatible.

I wasn't able to find many online examples of the boost `named_semaphore`, but I noticed that [the boost test code](https://github.com/boostorg/interprocess/blob/3b5da7b0c1e879e9c28407725fd53b919551c648/test/named_semaphore_test.cpp#L101) uses slightly different syntax to create the semaphore.

One unexpected thing I found when working on this project is that on Windows: ["The semaphore object is destroyed when its last handle has been closed."](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createsemaphorea). So another good test would be to confirm that you always have an open handle to the semaphore, otherwise Windows will destroy the semaphore.

Let me know if that helps.

**Comment by Berttwm** [comment]
Hi,

Thanks for getting back regarding this issue. I did note that ["The semaphore object is destroyed when its last handle has been closed."](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createsemaphorea) and was careful to leave the handle "opened" for the CPP Boost iteration, if you refer to my CPP code segment, I system paused the code at line 39 which meant the semaphore was still "alive" and not yet dereferenced. As the handle on Python could not even be initialized, I think Boost semaphores for windows (in your findings `CreateSemaphoreA()`) may be incompatible with the `CreateSemaphoreW()` which `semaphore_win_ctypes` uses. The underlying mechanism as to why this is so remains unclear to me.

I unfortunately scrapped the Boost implementation as it did not seem to work. However, I did have success going instead with `CreateSemaphoreW()` through the `#include <Windows.h>` import which immediately worked. (Caveat: I need to first initialize the Semaphore on the CPP program prior to executing my python script). 

Python code...

![image](https://user-images.githubusercontent.com/44689249/159866789-3c747cb3-02a1-4177-846f-854bb89b481a.png) 

Cpp code...

![image](https://user-images.githubusercontent.com/44689249/159866886-04acabcf-752a-421a-bb68-f947f3225745.png)

Thank you for assisting me. This issue is resolved on my end.
